/**
 * huffman_table.h — Auto-generated by huffman_analysis.py --emit
 * Generated : 2026-04-06 20:13 UTC
 * Sources   : 192.168.29.111, 192.168.29.87, 192.168.29.101
 * Corpus    : 6,320,178 chars
 * N-grams   : 127 (sorted lexicographically for binary search)
 * Alphabet  : 255 symbols — 0x00 EOM, 0x01-0x7E ASCII, 0x7F unused, 0x80-0xFE n-gram
 * Max depth : 24 bits
 *
 * Compression on corpus:
 *   Original  : 50,561,424 bits (6,320,178 bytes)
 *   Compressed: 15,296,935 bits (1,912,116 bytes, 30.3% of original)
 *   Savings   : 35,264,489 bits (69.7% reduction)
 *
 * HUFFMAN_TABLE entry (uint32_t):
 *   bits [31:27]  code length in bits
 *   bits [26: 0]  canonical Huffman code, MSB first, right-justified
 *
 * Encoder tokeniser (C pseudocode):
 *   uint8_t lo = pgm_read_byte(&NGRAM_FIRST[c]);
 *   uint8_t hi = pgm_read_byte(&NGRAM_LAST[c]);
 *   for (j = lo; j < hi; j++) — try candidate n-grams, pick longest match
 *   emit HUFFMAN_TABLE[0x80|j]  or  HUFFMAN_TABLE[c] for single char
 *
 * Decoder loop: see HuffmanDecoder.h — O(HUFF_MAX_CODE_BITS) per symbol.
 */

#pragma once
#include <pgmspace.h>
#include <stdint.h>

#define NGRAM_COUNT           127
#define NGRAM_MAX_LEN           8
#define HUFFMAN_ALPHABET_SIZE 255
#define HUFF_MAX_CODE_BITS     21

// N-gram string pool sorted lexicographically.
// Entry i → token byte (0x80 | i).  8 chars + NUL, null-padded.
// Use NGRAM_FIRST[c]/NGRAM_LAST[c] to find candidates for a given first char.
// clang-format off
static const char NGRAM_TABLE[NGRAM_COUNT][NGRAM_MAX_LEN + 1] PROGMEM = {
    " - ",  // [  0] 0x80  hlen= 9  n=3
    " event",  // [  1] 0x81  hlen=21  n=6
    " heap: ",  // [  2] 0x82  hlen=17  n=7
    " i",  // [  3] 0x83  hlen= 8  n=2
    " is disa",  // [  4] 0x84  hlen= 6  n=8
    " publish",  // [  5] 0x85  hlen=19  n=8
    "\",\"",  // [  6] 0x86  hlen= 7  n=3
    "\",\"freeH",  // [  7] 0x87  hlen= 8  n=8
    "\":",  // [  8] 0x88  hlen= 6  n=2
    "\":\"",  // [  9] 0x89  hlen= 8  n=3
    "\":\"192.1",  // [ 10] 0x8a  hlen=18  n=8
    "\":0,\"",  // [ 11] 0x8b  hlen= 8  n=5
    ", uptime",  // [ 12] 0x8c  hlen= 8  n=8
    ",\"",  // [ 13] 0x8d  hlen= 8  n=2
    ",\"heapLo",  // [ 14] 0x8e  hlen= 8  n=8
    ",\"ip\":\"1",  // [ 15] 0x8f  hlen=18  n=8
    ",\"minimu",  // [ 16] 0x90  hlen= 8  n=8
    ",\"time\":",  // [ 17] 0x91  hlen= 8  n=8
    ",\"uptime",  // [ 18] 0x92  hlen= 8  n=8
    "/monitor",  // [ 19] 0x93  hlen= 8  n=8
    "0,\"",  // [ 20] 0x94  hlen= 9  n=3
    "0,\"ip\":\"",  // [ 21] 0x95  hlen= 8  n=8
    "0min\":",  // [ 22] 0x96  hlen=21  n=6
    "15547274",  // [ 23] 0x97  hlen= 8  n=8
    "192.168.",  // [ 24] 0x98  hlen= 8  n=8
    "2827530",  // [ 25] 0x99  hlen= 8  n=7
    "68,\"mini",  // [ 26] 0x9a  hlen= 8  n=8
    "68.29.",  // [ 27] 0x9b  hlen=18  n=6
    "8,\"minim",  // [ 28] 0x9c  hlen=11  n=8
    "92.168.",  // [ 29] 0x9d  hlen=18  n=7
    ": ",  // [ 30] 0x9e  hlen= 6  n=2
    ": rgbw",  // [ 31] 0x9f  hlen= 8  n=6
    "===",  // [ 32] 0xa0  hlen=15  n=3
    "======",  // [ 33] 0xa1  hlen=11  n=6
    "========",  // [ 34] 0xa2  hlen=10  n=8
    "APPL",  // [ 35] 0xa3  hlen=14  n=4
    "APPLEDCt",  // [ 36] 0xa4  hlen= 6  n=8
    "Applicat",  // [ 37] 0xa5  hlen= 8  n=8
    "Ctrl",  // [ 38] 0xa6  hlen=13  n=4
    "Enabled\"",  // [ 39] 0xa7  hlen= 8  n=8
    "ErrUpt",  // [ 40] 0xa8  hlen=10  n=6
    "Free hea",  // [ 41] 0xa9  hlen= 8  n=8
    "Heap10",  // [ 42] 0xaa  hlen= 9  n=6
    "LED",  // [ 43] 0xab  hlen=11  n=3
    "Not",  // [ 44] 0xac  hlen=19  n=3
    "NotInSch",  // [ 45] 0xad  hlen= 6  n=8
    "Telemetr",  // [ 46] 0xae  hlen= 8  n=8
    "[CFGDB] ",  // [ 47] 0xaf  hlen= 6  n=8
    "ab",  // [ 48] 0xb0  hlen=18  n=2
    "abled\"",  // [ 49] 0xb1  hlen=18  n=6
    "ap",  // [ 50] 0xb2  hlen=12  n=2
    "bled",  // [ 51] 0xb3  hlen= 6  n=4
    "ch",  // [ 52] 0xb4  hlen=13  n=2
    "che",  // [ 53] 0xb5  hlen= 9  n=3
    "e\":",  // [ 54] 0xb6  hlen=10  n=3
    "e\":0} t",  // [ 55] 0xb7  hlen=11  n=7
    "ea",  // [ 56] 0xb8  hlen= 8  n=2
    "ed",  // [ 57] 0xb9  hlen= 9  n=2
    "eeHeap1",  // [ 58] 0xba  hlen=21  n=7
    "eeHeapR",  // [ 59] 0xbb  hlen=11  n=7
    "elemetry",  // [ 60] 0xbc  hlen= 9  n=8
    "em",  // [ 61] 0xbd  hlen=17  n=2
    "ema",  // [ 62] 0xbe  hlen=10  n=3
    "ema \"",  // [ 63] 0xbf  hlen= 7  n=5
    "ema \"u",  // [ 64] 0xc0  hlen= 8  n=6
    "en",  // [ 65] 0xc1  hlen= 9  n=2
    "ent",  // [ 66] 0xc2  hlen=16  n=3
    "ents",  // [ 67] 0xc3  hlen= 9  n=4
    "er",  // [ 68] 0xc4  hlen= 9  n=2
    "erv",  // [ 69] 0xc5  hlen=20  n=3
    "erver::",  // [ 70] 0xc6  hlen= 9  n=7
    "eve",  // [ 71] 0xc7  hlen=17  n=3
    "event",  // [ 72] 0xc8  hlen=10  n=5
    "eventser",  // [ 73] 0xc9  hlen=21  n=8
    "free",  // [ 74] 0xca  hlen=17  n=4
    "g {\"id\"",  // [ 75] 0xcb  hlen= 8  n=7
    "he",  // [ 76] 0xcc  hlen= 9  n=2
    "heap",  // [ 77] 0xcd  hlen=19  n=4
    "heapLow",  // [ 78] 0xce  hlen=10  n=7
    "ic: rgb",  // [ 79] 0xcf  hlen=11  n=7
    "icat",  // [ 80] 0xd0  hlen= 9  n=4
    "id\":",  // [ 81] 0xd1  hlen= 9  n=4
    "im",  // [ 82] 0xd2  hlen=10  n=2
    "in",  // [ 83] 0xd3  hlen= 9  n=2
    "ing",  // [ 84] 0xd4  hlen=10  n=3
    "ing ",  // [ 85] 0xd5  hlen= 8  n=4
    "ionWebse",  // [ 86] 0xd6  hlen= 8  n=8
    "ip\":\"1",  // [ 87] 0xd7  hlen=21  n=6
    "is",  // [ 88] 0xd8  hlen=14  n=2
    "l ",  // [ 89] 0xd9  hlen= 9  n=2
    "le",  // [ 90] 0xda  hlen=10  n=2
    "led",  // [ 91] 0xdb  hlen=12  n=3
    "me",  // [ 92] 0xdc  hlen= 8  n=2
    "me\":0} t",  // [ 93] 0xdd  hlen= 9  n=8
    "mfreeHea",  // [ 94] 0xde  hlen= 8  n=8
    "mini",  // [ 95] 0xdf  hlen=11  n=4
    "monitor",  // [ 96] 0xe0  hlen=19  n=7
    "mumf",  // [ 97] 0xe1  hlen= 8  n=4
    "nt",  // [ 98] 0xe2  hlen= 9  n=2
    "ntserver",  // [ 99] 0xe3  hlen= 6  n=8
    "o topic",  // [100] 0xe4  hlen= 8  n=7
    "on",  // [101] 0xe5  hlen= 6  n=2
    "otI",  // [102] 0xe6  hlen=20  n=3
    "p10min\":",  // [103] 0xe7  hlen= 9  n=8
    "pRuntime",  // [104] 0xe8  hlen= 8  n=8
    "pti",  // [105] 0xe9  hlen=19  n=3
    "re",  // [106] 0xea  hlen= 7  n=2
    "rl",  // [107] 0xeb  hlen= 9  n=2
    "rl - eve",  // [108] 0xec  hlen= 6  n=8
    "rver:",  // [109] 0xed  hlen= 8  n=5
    "se",  // [110] 0xee  hlen= 8  n=2
    "ser",  // [111] 0xef  hlen= 9  n=3
    "ti",  // [112] 0xf0  hlen= 9  n=2
    "time",  // [113] 0xf1  hlen=21  n=4
    "tr",  // [114] 0xf2  hlen=11  n=2
    "ts",  // [115] 0xf3  hlen= 8  n=2
    "ublishin",  // [116] 0xf4  hlen= 8  n=8
    "umfr",  // [117] 0xf5  hlen=11  n=4
    "untime\"",  // [118] 0xf6  hlen=11  n=7
    "uptime\":",  // [119] 0xf7  hlen=12  n=8
    "ve",  // [120] 0xf8  hlen= 9  n=2
    "vent",  // [121] 0xf9  hlen= 9  n=4
    "ver",  // [122] 0xfa  hlen=21  n=3
    "wErrUpti",  // [123] 0xfb  hlen= 8  n=8
    "y MQTT ",  // [124] 0xfc  hlen=19  n=7
    "y MQTT p",  // [125] 0xfd  hlen= 8  n=8
    "} to top"   // [126] 0xfe  hlen=11  n=8
};
// clang-format on

// Length of each n-gram (chars, excl. NUL terminator).
static const uint8_t NGRAM_LEN[NGRAM_COUNT] PROGMEM = {
    3, 6, 7, 2, 8, 8, 3, 8, 2, 3, 8, 5, 8, 2, 8, 8,
    8, 8, 8, 8, 3, 8, 6, 8, 8, 7, 8, 6, 8, 7, 2, 6,
    3, 6, 8, 4, 8, 8, 4, 8, 6, 8, 6, 3, 3, 8, 8, 8,
    2, 6, 2, 4, 2, 3, 3, 7, 2, 2, 7, 7, 8, 2, 3, 5,
    6, 2, 3, 4, 2, 3, 7, 3, 5, 8, 4, 7, 2, 4, 7, 7,
    4, 4, 2, 2, 3, 4, 8, 6, 2, 2, 2, 3, 2, 8, 8, 4,
    7, 4, 2, 8, 7, 2, 3, 8, 8, 3, 2, 2, 8, 5, 2, 3,
    2, 4, 2, 2, 8, 4, 7, 8, 2, 4, 3, 8, 7, 8, 8
};

// NGRAM_FIRST[c]: first index in NGRAM_TABLE of n-grams starting with char c.
// 255 = no n-gram starts with this character.
static const uint8_t NGRAM_FIRST[128] PROGMEM = {
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
      0, 255,   6, 255, 255, 255, 255, 255, 255, 255, 255, 255,  12, 255, 255,  19,
     20,  23,  25, 255, 255, 255,  26, 255,  28,  29,  30, 255, 255,  32, 255, 255,
    255,  35, 255,  38, 255,  39,  41, 255,  42, 255, 255, 255,  43, 255,  44, 255,
    255, 255, 255, 255,  46, 255, 255, 255, 255, 255, 255,  47, 255, 255, 255, 255,
    255,  48,  51,  52, 255,  54,  74,  75,  76,  79, 255, 255,  89,  92,  98, 100,
    103, 255, 106, 110, 112, 116, 120, 123, 255, 124, 255, 255, 255, 126, 255, 255
};

// NGRAM_LAST[c]: exclusive end index for n-grams starting with char c.
// 255 = no n-gram starts with this character.
static const uint8_t NGRAM_LAST[128] PROGMEM = {
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
      6, 255,  12, 255, 255, 255, 255, 255, 255, 255, 255, 255,  19, 255, 255,  20,
     23,  25,  26, 255, 255, 255,  28, 255,  29,  30,  32, 255, 255,  35, 255, 255,
    255,  38, 255,  39, 255,  41,  42, 255,  43, 255, 255, 255,  44, 255,  46, 255,
    255, 255, 255, 255,  47, 255, 255, 255, 255, 255, 255,  48, 255, 255, 255, 255,
    255,  51,  52,  54, 255,  74,  75,  76,  79,  89, 255, 255,  92,  98, 100, 103,
    106, 255, 110, 112, 116, 120, 123, 124, 255, 126, 255, 255, 255, 127, 255, 255
};

// Huffman code table indexed by token byte value (255 entries).
// bits[31:27] = code length in bits,  bits[26:0] = canonical code (MSB first).
// clang-format off
static const uint32_t HUFFMAN_TABLE[HUFFMAN_ALPHABET_SIZE] PROGMEM = {
    0x9003FFF0,  // 0x00 NUL (EOM)             len=18  freq=7
    0x00000000,  // 0x01 SOH  (unused)
    0x00000000,  // 0x02 STX  (unused)
    0x00000000,  // 0x03 ETX  (unused)
    0x00000000,  // 0x04 EOT  (unused)
    0x00000000,  // 0x05 ENQ  (unused)
    0x00000000,  // 0x06 ACK  (unused)
    0x00000000,  // 0x07 BEL  (unused)
    0x00000000,  // 0x08 BS  (unused)
    0x78007FF6,  // 0x09 HT                    len=15  freq=64
    0x20000000,  // 0x0a LF                    len= 4  freq=118,224
    0x00000000,  // 0x0b VT  (unused)
    0x00000000,  // 0x0c FF  (unused)
    0x00000000,  // 0x0d CR  (unused)
    0x00000000,  // 0x0e SO  (unused)
    0x00000000,  // 0x0f SI  (unused)
    0x00000000,  // 0x10 DLE  (unused)
    0x00000000,  // 0x11 DC1  (unused)
    0x00000000,  // 0x12 DC2  (unused)
    0x00000000,  // 0x13 DC3  (unused)
    0x00000000,  // 0x14 DC4  (unused)
    0x00000000,  // 0x15 NAK  (unused)
    0x00000000,  // 0x16 SYN  (unused)
    0x00000000,  // 0x17 ETB  (unused)
    0x00000000,  // 0x18 CAN  (unused)
    0x00000000,  // 0x19 EM  (unused)
    0x00000000,  // 0x1a SUB  (unused)
    0x78007FF7,  // 0x1b ESC                   len=15  freq=76
    0x00000000,  // 0x1c FS  (unused)
    0x00000000,  // 0x1d GS  (unused)
    0x00000000,  // 0x1e RS  (unused)
    0x00000000,  // 0x1f US  (unused)
    0x3000000A,  // 0x20 ' '                   len= 6  freq=36,352
    0xA81FFFEC,  // 0x21 '!'                   len=21  freq=1
    0x3000000B,  // 0x22 '"'                   len= 6  freq=49,046
    0x70003FF6,  // 0x23 '#'                   len=14  freq=113
    0xA81FFFED,  // 0x24 '$'                   len=21  freq=1
    0xA81FFFEE,  // 0x25 '%'                   len=21  freq=1
    0xA81FFFEF,  // 0x26 '&'                   len=21  freq=1
    0x480001D6,  // 0x27 "'"                   len= 9  freq=3,366
    0x68001FF4,  // 0x28 '('                   len=13  freq=233
    0x68001FF5,  // 0x29 ')'                   len=13  freq=233
    0xA81FFFF0,  // 0x2a '*'                   len=21  freq=1
    0xA81FFFF1,  // 0x2b '+'                   len=21  freq=1
    0x480001D7,  // 0x2c ','                   len= 9  freq=5,606
    0x580007EA,  // 0x2d '-'                   len=11  freq=1,062
    0x38000052,  // 0x2e '.'                   len= 7  freq=20,085
    0x38000053,  // 0x2f '/'                   len= 7  freq=15,827
    0x3000000C,  // 0x30 '0'                   len= 6  freq=47,925
    0x28000002,  // 0x31 '1'                   len= 5  freq=64,773
    0x28000003,  // 0x32 '2'                   len= 5  freq=87,877
    0x3000000D,  // 0x33 '3'                   len= 6  freq=43,547
    0x3000000E,  // 0x34 '4'                   len= 6  freq=33,987
    0x3000000F,  // 0x35 '5'                   len= 6  freq=26,887
    0x30000010,  // 0x36 '6'                   len= 6  freq=31,944
    0x30000011,  // 0x37 '7'                   len= 6  freq=25,344
    0x30000012,  // 0x38 '8'                   len= 6  freq=38,081
    0x30000013,  // 0x39 '9'                   len= 6  freq=30,418
    0x38000054,  // 0x3a ':'                   len= 7  freq=22,595
    0x8000FFF8,  // 0x3b ';'                   len=16  freq=38
    0x580007EB,  // 0x3c '<'                   len=11  freq=1,339
    0x60000FF2,  // 0x3d '='                   len=12  freq=453
    0x580007EC,  // 0x3e '>'                   len=11  freq=1,401
    0xA00FFFF2,  // 0x3f '?'                   len=20  freq=2
    0x9003FFF1,  // 0x40 '@'                   len=18  freq=9
    0x70003FF7,  // 0x41 'A'                   len=14  freq=110
    0x70003FF8,  // 0x42 'B'                   len=14  freq=166
    0x400000BA,  // 0x43 'C'                   len= 8  freq=10,836
    0x68001FF6,  // 0x44 'D'                   len=13  freq=260
    0x400000BB,  // 0x45 'E'                   len= 8  freq=7,791
    0x500003E8,  // 0x46 'F'                   len=10  freq=2,317
    0x78007FF8,  // 0x47 'G'                   len=15  freq=92
    0x480001D8,  // 0x48 'H'                   len= 9  freq=4,673
    0x60000FF3,  // 0x49 'I'                   len=12  freq=578
    0x500003E9,  // 0x4a 'J'                   len=10  freq=1,644
    0xA81FFFF2,  // 0x4b 'K'                   len=21  freq=1
    0x580007ED,  // 0x4c 'L'                   len=11  freq=1,485
    0x68001FF7,  // 0x4d 'M'                   len=13  freq=290
    0x500003EA,  // 0x4e 'N'                   len=10  freq=1,920
    0x480001D9,  // 0x4f 'O'                   len= 9  freq=3,198
    0x500003EB,  // 0x50 'P'                   len=10  freq=2,491
    0x9807FFF0,  // 0x51 'Q'                   len=19  freq=5
    0x400000BC,  // 0x52 'R'                   len= 8  freq=7,726
    0x400000BD,  // 0x53 'S'                   len= 8  freq=10,008
    0x400000BE,  // 0x54 'T'                   len= 8  freq=11,007
    0x9807FFF1,  // 0x55 'U'                   len=19  freq=6
    0x68001FF8,  // 0x56 'V'                   len=13  freq=257
    0x78007FF9,  // 0x57 'W'                   len=15  freq=59
    0xA81FFFF3,  // 0x58 'X'                   len=21  freq=1
    0xA81FFFF4,  // 0x59 'Y'                   len=21  freq=1
    0xA81FFFF5,  // 0x5a 'Z'                   len=21  freq=1
    0x78007FFA,  // 0x5b '['                   len=15  freq=79
    0xA81FFFF6,  // 0x5c '\\'                  len=21  freq=1
    0x9807FFF2,  // 0x5d ']'                   len=19  freq=3
    0xA81FFFF7,  // 0x5e '^'                   len=21  freq=1
    0x400000BF,  // 0x5f '_'                   len= 8  freq=7,357
    0xA00FFFF3,  // 0x60 '`'                   len=20  freq=1
    0x30000014,  // 0x61 'a'                   len= 6  freq=43,393
    0x480001DA,  // 0x62 'b'                   len= 9  freq=4,333
    0x30000015,  // 0x63 'c'                   len= 6  freq=31,916
    0x30000016,  // 0x64 'd'                   len= 6  freq=25,439
    0x30000017,  // 0x65 'e'                   len= 6  freq=42,014
    0x38000055,  // 0x66 'f'                   len= 7  freq=13,634
    0x30000018,  // 0x67 'g'                   len= 6  freq=32,541
    0x38000056,  // 0x68 'h'                   len= 7  freq=21,935
    0x30000019,  // 0x69 'i'                   len= 6  freq=28,153
    0x480001DB,  // 0x6a 'j'                   len= 9  freq=6,334
    0x400000C0,  // 0x6b 'k'                   len= 8  freq=9,834
    0x3000001A,  // 0x6c 'l'                   len= 6  freq=30,538
    0x400000C1,  // 0x6d 'm'                   len= 8  freq=12,268
    0x38000057,  // 0x6e 'n'                   len= 7  freq=22,827
    0x3000001B,  // 0x6f 'o'                   len= 6  freq=48,979
    0x3000001C,  // 0x70 'p'                   len= 6  freq=44,717
    0x400000C2,  // 0x71 'q'                   len= 8  freq=7,072
    0x3000001D,  // 0x72 'r'                   len= 6  freq=35,303
    0x3000001E,  // 0x73 's'                   len= 6  freq=46,864
    0x28000004,  // 0x74 't'                   len= 5  freq=66,039
    0x38000058,  // 0x75 'u'                   len= 7  freq=17,016
    0x400000C3,  // 0x76 'v'                   len= 8  freq=7,486
    0x38000059,  // 0x77 'w'                   len= 7  freq=24,788
    0x480001DC,  // 0x78 'x'                   len= 9  freq=6,046
    0x60000FF4,  // 0x79 'y'                   len=12  freq=535
    0x60000FF5,  // 0x7a 'z'                   len=12  freq=559
    0x400000C4,  // 0x7b '{'                   len= 8  freq=12,379
    0x60000FF6,  // 0x7c '|'                   len=12  freq=635
    0x400000C5,  // 0x7d '}'                   len= 8  freq=12,358
    0xA81FFFF8,  // 0x7e '~'                   len=21  freq=1
    0x00000000,  // 0x7f [unused]  (unused)
    0x480001DD,  // 0x80 " - "                 len= 9  freq=5,973
    0xA81FFFF9,  // 0x81 " event"              len=21  freq=1
    0x8801FFF4,  // 0x82 " heap: "             len=17  freq=20
    0x400000C6,  // 0x83 " i"                  len= 8  freq=7,052
    0x3000001F,  // 0x84 " is disa"            len= 6  freq=37,192
    0x9807FFF3,  // 0x85 " publish"            len=19  freq=5
    0x3800005A,  // 0x86 "\",\""               len= 7  freq=14,033
    0x400000C7,  // 0x87 "\",\"freeH"          len= 8  freq=8,351
    0x30000020,  // 0x88 "\":"                 len= 6  freq=43,167
    0x400000C8,  // 0x89 "\":\""               len= 8  freq=11,940
    0x9003FFF2,  // 0x8a "\":\"192.1"          len=18  freq=9
    0x400000C9,  // 0x8b "\":0,\""             len= 8  freq=10,458
    0x400000CA,  // 0x8c ", uptime"            len= 8  freq=8,359
    0x400000CB,  // 0x8d ",\""                 len= 8  freq=8,304
    0x400000CC,  // 0x8e ",\"heapLo"           len= 8  freq=6,774
    0x9003FFF3,  // 0x8f ",\"ip\":\"1"         len=18  freq=9
    0x400000CD,  // 0x90 ",\"minimu"           len= 8  freq=8,107
    0x400000CE,  // 0x91 ",\"time\":"          len= 8  freq=8,351
    0x400000CF,  // 0x92 ",\"uptime"           len= 8  freq=7,620
    0x400000D0,  // 0x93 "/monitor"            len= 8  freq=8,351
    0x480001DE,  // 0x94 "0,\""                len= 9  freq=3,722
    0x400000D1,  // 0x95 "0,\"ip\":\""         len= 8  freq=8,350
    0xA81FFFFA,  // 0x96 "0min\":"             len=21  freq=1
    0x400000D2,  // 0x97 "15547274"            len= 8  freq=7,146
    0x400000D3,  // 0x98 "192.168."            len= 8  freq=9,224
    0x400000D4,  // 0x99 "2827530"             len= 8  freq=8,454
    0x400000D5,  // 0x9a "68,\"mini"           len= 8  freq=6,398
    0x9003FFF4,  // 0x9b "68.29."              len=18  freq=9
    0x580007EE,  // 0x9c "8,\"minim"           len=11  freq=1,002
    0x9003FFF5,  // 0x9d "92.168."             len=18  freq=10
    0x30000021,  // 0x9e ": "                  len= 6  freq=36,935
    0x400000D6,  // 0x9f ": rgbw"              len= 8  freq=7,547
    0x78007FFB,  // 0xa0 "==="                 len=15  freq=106
    0x580007EF,  // 0xa1 "======"              len=11  freq=1,076
    0x500003EC,  // 0xa2 "========"            len=10  freq=2,167
    0x70003FF9,  // 0xa3 "APPL"                len=14  freq=210
    0x30000022,  // 0xa4 "APPLEDCt"            len= 6  freq=37,192
    0x400000D7,  // 0xa5 "Applicat"            len= 8  freq=9,344
    0x68001FF9,  // 0xa6 "Ctrl"                len=13  freq=210
    0x400000D8,  // 0xa7 "Enabled\""           len= 8  freq=11,057
    0x500003ED,  // 0xa8 "ErrUpt"              len=10  freq=1,577
    0x400000D9,  // 0xa9 "Free hea"            len= 8  freq=8,369
    0x480001DF,  // 0xaa "Heap10"              len= 9  freq=4,341
    0x580007F0,  // 0xab "LED"                 len=11  freq=1,394
    0x9807FFF4,  // 0xac "Not"                 len=19  freq=5
    0x30000023,  // 0xad "NotInSch"            len= 6  freq=36,153
    0x400000DA,  // 0xae "Telemetr"            len= 8  freq=8,361
    0x30000024,  // 0xaf "[CFGDB] "            len= 6  freq=34,607
    0x9003FFF6,  // 0xb0 "ab"                  len=18  freq=7
    0x9003FFF7,  // 0xb1 "abled\""             len=18  freq=9
    0x60000FF7,  // 0xb2 "ap"                  len=12  freq=465
    0x30000025,  // 0xb3 "bled"                len= 6  freq=37,192
    0x68001FFA,  // 0xb4 "ch"                  len=13  freq=380
    0x480001E0,  // 0xb5 "che"                 len= 9  freq=5,755
    0x500003EE,  // 0xb6 "e\":"                len=10  freq=2,309
    0x580007F1,  // 0xb7 "e\":0} t"            len=11  freq=1,353
    0x400000DB,  // 0xb8 "ea"                  len= 8  freq=11,692
    0x480001E1,  // 0xb9 "ed"                  len= 9  freq=6,216
    0xA81FFFFB,  // 0xba "eeHeap1"             len=21  freq=1
    0x580007F2,  // 0xbb "eeHeapR"             len=11  freq=1,001
    0x480001E2,  // 0xbc "elemetry"            len= 9  freq=5,534
    0x8801FFF5,  // 0xbd "em"                  len=17  freq=20
    0x500003EF,  // 0xbe "ema"                 len=10  freq=1,611
    0x3800005B,  // 0xbf "ema \""              len= 7  freq=23,510
    0x400000DC,  // 0xc0 "ema \"u"             len= 8  freq=11,032
    0x480001E3,  // 0xc1 "en"                  len= 9  freq=5,932
    0x8000FFF9,  // 0xc2 "ent"                 len=16  freq=38
    0x480001E4,  // 0xc3 "ents"                len= 9  freq=5,948
    0x480001E5,  // 0xc4 "er"                  len= 9  freq=5,920
    0xA00FFFF4,  // 0xc5 "erv"                 len=20  freq=3
    0x480001E6,  // 0xc6 "erver::"             len= 9  freq=5,948
    0x8801FFF6,  // 0xc7 "eve"                 len=17  freq=28
    0x500003F0,  // 0xc8 "event"               len=10  freq=2,090
    0xA81FFFFC,  // 0xc9 "eventser"            len=21  freq=1
    0x8801FFF7,  // 0xca "free"                len=17  freq=25
    0x400000DD,  // 0xcb "g {\"id\""           len= 8  freq=8,351
    0x480001E7,  // 0xcc "he"                  len= 9  freq=5,759
    0x9807FFF5,  // 0xcd "heap"                len=19  freq=5
    0x500003F1,  // 0xce "heapLow"             len=10  freq=1,577
    0x580007F3,  // 0xcf "ic: rgb"             len=11  freq=804
    0x480001E8,  // 0xd0 "icat"                len= 9  freq=5,755
    0x480001E9,  // 0xd1 "id\":"               len= 9  freq=5,966
    0x500003F2,  // 0xd2 "im"                  len=10  freq=1,610
    0x480001EA,  // 0xd3 "in"                  len= 9  freq=4,707
    0x500003F3,  // 0xd4 "ing"                 len=10  freq=2,132
    0x400000DE,  // 0xd5 "ing "                len= 8  freq=7,368
    0x400000DF,  // 0xd6 "ionWebse"            len= 8  freq=9,268
    0xA81FFFFD,  // 0xd7 "ip\":\"1"            len=21  freq=1
    0x70003FFA,  // 0xd8 "is"                  len=14  freq=135
    0x480001EB,  // 0xd9 "l "                  len= 9  freq=5,813
    0x500003F4,  // 0xda "le"                  len=10  freq=2,169
    0x60000FF8,  // 0xdb "led"                 len=12  freq=744
    0x400000E0,  // 0xdc "me"                  len= 8  freq=7,762
    0x480001EC,  // 0xdd "me\":0} t"           len= 9  freq=6,194
    0x400000E1,  // 0xde "mfreeHea"            len= 8  freq=8,107
    0x580007F4,  // 0xdf "mini"                len=11  freq=1,195
    0x9807FFF6,  // 0xe0 "monitor"             len=19  freq=5
    0x400000E2,  // 0xe1 "mumf"                len= 8  freq=7,593
    0x480001ED,  // 0xe2 "nt"                  len= 9  freq=5,791
    0x30000026,  // 0xe3 "ntserver"            len= 6  freq=37,192
    0x400000E3,  // 0xe4 "o topic"             len= 8  freq=7,547
    0x30000027,  // 0xe5 "on"                  len= 6  freq=25,462
    0xA00FFFF5,  // 0xe6 "otI"                 len=20  freq=3
    0x480001EE,  // 0xe7 "p10min\":"           len= 9  freq=4,009
    0x400000E4,  // 0xe8 "pRuntime"            len= 8  freq=7,350
    0x9807FFF7,  // 0xe9 "pti"                 len=19  freq=5
    0x3800005C,  // 0xea "re"                  len= 7  freq=17,034
    0x480001EF,  // 0xeb "rl"                  len= 9  freq=5,531
    0x30000028,  // 0xec "rl - eve"            len= 6  freq=37,192
    0x400000E5,  // 0xed "rver:"               len= 8  freq=9,268
    0x400000E6,  // 0xee "se"                  len= 8  freq=8,923
    0x480001F0,  // 0xef "ser"                 len= 9  freq=5,512
    0x480001F1,  // 0xf0 "ti"                  len= 9  freq=4,950
    0xA81FFFFE,  // 0xf1 "time"                len=21  freq=1
    0x580007F5,  // 0xf2 "tr"                  len=11  freq=982
    0x400000E7,  // 0xf3 "ts"                  len= 8  freq=7,745
    0x400000E8,  // 0xf4 "ublishin"            len= 8  freq=8,351
    0x580007F6,  // 0xf5 "umfr"                len=11  freq=1,002
    0x580007F7,  // 0xf6 "untime\""            len=11  freq=1,001
    0x60000FF9,  // 0xf7 "uptime\":"           len=12  freq=731
    0x480001F2,  // 0xf8 "ve"                  len= 9  freq=5,425
    0x480001F3,  // 0xf9 "vent"                len= 9  freq=5,948
    0xA81FFFFF,  // 0xfa "ver"                 len=21  freq=1
    0x400000E9,  // 0xfb "wErrUpti"            len= 8  freq=6,774
    0x9807FFF8,  // 0xfc "y MQTT "             len=19  freq=5
    0x400000EA,  // 0xfd "y MQTT p"            len= 8  freq=8,351
    0x580007F8   // 0xfe "} to top"            len=11  freq=804
};
// clang-format on

// Canonical Huffman decode tables.
// Decoder: accumulate one bit per step; at length L check
//   if code in [FIRST[L], FIRST[L]+COUNT[L]):
//     symbol = SYMBOLS[GROUP[L] + code - FIRST[L]]

// Number of codes at each bit-length (index 0 unused).
static const uint8_t HUFF_DECODE_COUNT[HUFF_MAX_CODE_BITS + 1] PROGMEM = {
    0, 0, 0, 0, 1, 3, 31, 11, 49, 30, 13, 15, 8, 7, 5, 6, 2, 4, 8, 9, 4, 20
};

// First canonical code value at each bit-length.
static const uint32_t HUFF_DECODE_FIRST[HUFF_MAX_CODE_BITS + 1] PROGMEM = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000002, 0x0000000A, 0x00000052, 0x000000BA, 0x000001D6, 0x000003E8, 0x000007EA, 0x00000FF2, 0x00001FF4, 0x00003FF6, 0x00007FF6, 0x0000FFF8, 0x0001FFF4, 0x0003FFF0, 0x0007FFF0, 0x000FFFF2, 0x001FFFEC
};

// Starting index in HUFF_DECODE_SYMBOLS for each bit-length.
static const uint16_t HUFF_DECODE_GROUP_OFFSET[HUFF_MAX_CODE_BITS + 1] PROGMEM = {
    0, 0, 0, 0, 0, 1, 4, 35, 46, 95, 125, 138, 153, 161, 168, 173, 179, 181, 185, 193, 202, 206
};

// Symbols in canonical order (226 entries).
static const uint8_t HUFF_DECODE_SYMBOLS[226] PROGMEM = {
    0x0a, 0x31, 0x32, 0x74, 0x20, 0x22, 0x30, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x61, 0x63,
    0x64, 0x65, 0x67, 0x69, 0x6c, 0x6f, 0x70, 0x72, 0x73, 0x84, 0x88, 0x9e, 0xa4, 0xad, 0xaf, 0xb3,
    0xe3, 0xe5, 0xec, 0x2e, 0x2f, 0x3a, 0x66, 0x68, 0x6e, 0x75, 0x77, 0x86, 0xbf, 0xea, 0x43, 0x45,
    0x52, 0x53, 0x54, 0x5f, 0x6b, 0x6d, 0x71, 0x76, 0x7b, 0x7d, 0x83, 0x87, 0x89, 0x8b, 0x8c, 0x8d,
    0x8e, 0x90, 0x91, 0x92, 0x93, 0x95, 0x97, 0x98, 0x99, 0x9a, 0x9f, 0xa5, 0xa7, 0xa9, 0xae, 0xb8,
    0xc0, 0xcb, 0xd5, 0xd6, 0xdc, 0xde, 0xe1, 0xe4, 0xe8, 0xed, 0xee, 0xf3, 0xf4, 0xfb, 0xfd, 0x27,
    0x2c, 0x48, 0x4f, 0x62, 0x6a, 0x78, 0x80, 0x94, 0xaa, 0xb5, 0xb9, 0xbc, 0xc1, 0xc3, 0xc4, 0xc6,
    0xcc, 0xd0, 0xd1, 0xd3, 0xd9, 0xdd, 0xe2, 0xe7, 0xeb, 0xef, 0xf0, 0xf8, 0xf9, 0x46, 0x4a, 0x4e,
    0x50, 0xa2, 0xa8, 0xb6, 0xbe, 0xc8, 0xce, 0xd2, 0xd4, 0xda, 0x2d, 0x3c, 0x3e, 0x4c, 0x9c, 0xa1,
    0xab, 0xb7, 0xbb, 0xcf, 0xdf, 0xf2, 0xf5, 0xf6, 0xfe, 0x3d, 0x49, 0x79, 0x7a, 0x7c, 0xb2, 0xdb,
    0xf7, 0x28, 0x29, 0x44, 0x4d, 0x56, 0xa6, 0xb4, 0x23, 0x41, 0x42, 0xa3, 0xd8, 0x09, 0x1b, 0x47,
    0x57, 0x5b, 0xa0, 0x3b, 0xc2, 0x82, 0xbd, 0xc7, 0xca, 0x00, 0x40, 0x8a, 0x8f, 0x9b, 0x9d, 0xb0,
    0xb1, 0x51, 0x55, 0x5d, 0x85, 0xac, 0xcd, 0xe0, 0xe9, 0xfc, 0x3f, 0x60, 0xc5, 0xe6, 0x21, 0x24,
    0x25, 0x26, 0x2a, 0x2b, 0x4b, 0x58, 0x59, 0x5a, 0x5c, 0x5e, 0x7e, 0x81, 0x96, 0xba, 0xc9, 0xd7,
    0xf1, 0xfa
};
