#include "../include/HuffmanDecoder.h"
#include "huffman_table.h" // generated by huffman_analysis.py --emit
#include <string.h>

HuffmanDecoder::HuffmanDecoder(HuffmanRingBuffer& rb)
    : _rb(rb), _decodedLen(0), _decodedPos(0),
      _bits(nullptr), _bitLen(0), _bitPos(0)
{
}

// ── Bit-level helpers ─────────────────────────────────────────────────────────

bool HuffmanDecoder::_hasBit() const
{
    return _bitPos < _bitLen;
}

uint8_t HuffmanDecoder::_nextBit()
{
    // Bytes are packed MSB first: bit 7 of byte 0 is bitstream position 0
    uint16_t byteIdx  = _bitPos >> 3;
    uint8_t  bitShift = 7u - (uint8_t)(_bitPos & 7u);
    _bitPos++;
    return (_bits[byteIdx] >> bitShift) & 1u;
}

// ── Canonical Huffman decoder ─────────────────────────────────────────────────
//
// Standard canonical decode loop: accumulate bits one at a time; at each
// length L check whether the accumulated L-bit code falls in the range
// [FIRST[L], FIRST[L] + COUNT[L]).  If so, map to the symbol.
//
// O(HUFF_MAX_CODE_BITS) comparisons per output symbol.

uint16_t HuffmanDecoder::_decodeSymbol()
{
    uint32_t code = 0;
    for(uint8_t L = 1; L <= HUFF_MAX_CODE_BITS; L++) {
        if(!_hasBit()) return 0xFFFFu;
        code = (code << 1) | _nextBit();

        uint8_t count = pgm_read_byte(&HUFF_DECODE_COUNT[L]);
        if(count == 0) continue;

        uint32_t first = pgm_read_dword(&HUFF_DECODE_FIRST[L]);
        if(code >= first && (code - first) < (uint32_t)count) {
            uint16_t offset = pgm_read_word(&HUFF_DECODE_GROUP_OFFSET[L]);
            return pgm_read_byte(&HUFF_DECODE_SYMBOLS[offset + (uint16_t)(code - first)]);
        }
    }
    return 0xFFFFu; // decode error
}

// ── Message decode ────────────────────────────────────────────────────────────

uint16_t HuffmanDecoder::_decodeMessage(const uint8_t* data, uint16_t lenBytes)
{
    _bits   = data;
    _bitLen = (uint16_t)(lenBytes * 8u);
    _bitPos = 0;

    uint16_t outLen = 0;
    // Leave NGRAM_MAX_LEN headroom so an n-gram expansion never overruns
    while(_hasBit() && outLen < (uint16_t)(DECODE_BUF_SIZE - NGRAM_MAX_LEN)) {
        uint16_t sym = _decodeSymbol();

        if(sym == 0xFFFFu) break;       // decode error
        if(sym == 0x0000u) break;       // NUL = end of message

        if(sym <= 0x7Eu) {
            // Single ASCII character
            _decodedBuf[outLen++] = (uint8_t)sym;
        } else if(sym >= 0x80u && sym <= 0xFEu) {
            // N-gram token: expand string from PROGMEM table
            uint8_t idx  = (uint8_t)(sym - 0x80u);
            uint8_t nlen = pgm_read_byte(&NGRAM_LEN[idx]);
            for(uint8_t j = 0; j < nlen; j++) {
                _decodedBuf[outLen++] = pgm_read_byte(&NGRAM_TABLE[idx][j]);
            }
        }
        // sym == 0x7F: unused slot — skip
    }
    return outLen;
}

bool HuffmanDecoder::_loadNextMessage()
{
    uint16_t compLen = 0;
    if(!_rb.read(_compBuf, COMP_BUF_SIZE, compLen)) return false;
    _decodedLen = _decodeMessage(_compBuf, compLen);
    _decodedPos = 0;
    return _decodedLen > 0;
}

// ── Static standalone frame decode ───────────────────────────────────────────

uint16_t HuffmanDecoder::decodeFrame(const uint8_t* data, uint16_t lenBytes,
                                     char* out, uint16_t outMax)
{
    const uint8_t* bits   = data;
    uint16_t       bitLen = (uint16_t)(lenBytes * 8u);
    uint16_t       bitPos = 0;
    uint16_t       outLen = 0;

    // Bit reader lambdas (captures by reference; inlined by compiler)
    auto hasBit   = [&]() -> bool    { return bitPos < bitLen; };
    auto nextBit  = [&]() -> uint8_t {
        uint16_t byteIdx  = bitPos >> 3;
        uint8_t  bitShift = 7u - (uint8_t)(bitPos & 7u);
        bitPos++;
        return (bits[byteIdx] >> bitShift) & 1u;
    };
    auto decodeSym = [&]() -> uint16_t {
        uint32_t code = 0;
        for(uint8_t L = 1; L <= HUFF_MAX_CODE_BITS; L++) {
            if(!hasBit()) return 0xFFFFu;
            code = (code << 1) | nextBit();
            uint8_t  count = pgm_read_byte(&HUFF_DECODE_COUNT[L]);
            if(count == 0) continue;
            uint32_t first = pgm_read_dword(&HUFF_DECODE_FIRST[L]);
            if(code >= first && (code - first) < (uint32_t)count) {
                uint16_t offset = pgm_read_word(&HUFF_DECODE_GROUP_OFFSET[L]);
                return pgm_read_byte(&HUFF_DECODE_SYMBOLS[offset + (uint16_t)(code - first)]);
            }
        }
        return 0xFFFFu;
    };

    while(hasBit() && outLen < (uint16_t)(outMax - NGRAM_MAX_LEN)) {
        uint16_t sym = decodeSym();
        if(sym == 0xFFFFu || sym == 0x0000u) break;
        if(sym <= 0x7Eu) {
            out[outLen++] = (char)sym;
        } else if(sym >= 0x80u && sym <= 0xFEu) {
            uint8_t idx  = (uint8_t)(sym - 0x80u);
            uint8_t nlen = pgm_read_byte(&NGRAM_LEN[idx]);
            for(uint8_t j = 0; j < nlen; j++) {
                out[outLen++] = (char)pgm_read_byte(&NGRAM_TABLE[idx][j]);
            }
        }
    }
    return outLen;
}

// ── IDataSourceStream ─────────────────────────────────────────────────────────

uint16_t HuffmanDecoder::readMemoryBlock(char* data, int bufSize)
{
    if(_decodedPos >= _decodedLen) {
        if(!_loadNextMessage()) return 0;
    }
    uint16_t avail  = _decodedLen - _decodedPos;
    uint16_t toRead = (avail < (uint16_t)bufSize) ? avail : (uint16_t)bufSize;
    memcpy(data, _decodedBuf + _decodedPos, toRead);
    return toRead;
}

bool HuffmanDecoder::seek(int len)
{
    _decodedPos = (uint16_t)(_decodedPos + (uint16_t)len);
    return true;
}

bool HuffmanDecoder::isFinished()
{
    return _rb.empty() && (_decodedPos >= _decodedLen);
}

int HuffmanDecoder::available()
{
    if(_decodedPos < _decodedLen) {
        return (int)(_decodedLen - _decodedPos);
    }
    return _rb.empty() ? 0 : -1; // -1 = more data available but compressed size unknown
}
