#include "../include/HuffmanEncoder.h"
#include "huffman_table.h" // generated by huffman_analysis.py --emit

HuffmanEncoder::HuffmanEncoder(HuffmanRingBuffer& rb)
    : _rb(rb), _inLen(0), _outLen(0), _bitBuf(0), _bitPos(0)
{
}

// ── Private ───────────────────────────────────────────────────────────────────

void HuffmanEncoder::_pushBit(uint8_t bit)
{
    _bitBuf = (uint8_t)((_bitBuf << 1) | (bit & 1u));
    if(++_bitPos == 8) {
        if(_outLen < OUTPUT_BUF_SIZE) {
            _outBuf[_outLen++] = _bitBuf;
        }
        _bitBuf = 0;
        _bitPos = 0;
    }
}

void HuffmanEncoder::_encodeSymbol(uint8_t sym)
{
    uint32_t entry = pgm_read_dword(&HUFFMAN_TABLE[sym]);
    uint8_t  len   = (uint8_t)(entry >> 27);
    uint32_t code  = entry & 0x07FFFFFFul;
    if(len == 0) return; // unused slot — skip silently
    for(int8_t shift = (int8_t)(len - 1); shift >= 0; shift--) {
        _pushBit((uint8_t)((code >> (uint8_t)shift) & 1u));
    }
}

// ── Public ────────────────────────────────────────────────────────────────────

size_t HuffmanEncoder::write(uint8_t c)
{
    if(_inLen < INPUT_BUF_SIZE) {
        _inBuf[_inLen++] = c;
    }
    if(c == '\0') {
        flush();
    }
    return 1;
}

size_t HuffmanEncoder::write(const uint8_t* data, size_t size)
{
    for(size_t i = 0; i < size; i++) {
        write(data[i]);
    }
    return size;
}

uint16_t HuffmanEncoder::flush()
{
    if(_inLen == 0) return 0;

    _outLen = 0;
    _bitBuf = 0;
    _bitPos = 0;

    // Tokenise and encode input
    uint16_t i = 0;
    while(i < _inLen) {
        uint8_t c   = _inBuf[i];
        uint8_t sym = c;
        uint8_t advance = 1;

        // Only printable ASCII is eligible for n-gram matching
        if(c >= 0x20 && c <= 0x7E) {
            uint8_t lo = pgm_read_byte(&NGRAM_FIRST[(uint8_t)c]);
            uint8_t hi = pgm_read_byte(&NGRAM_LAST[(uint8_t)c]);

            if(lo != 255) {
                // Try all candidate n-grams in [lo, hi), pick the longest match
                uint8_t bestIdx = 0xFF;
                uint8_t bestLen = 0;

                for(uint8_t j = lo; j < hi; j++) {
                    uint8_t nlen = pgm_read_byte(&NGRAM_LEN[j]);
                    if((uint16_t)(i + nlen) > _inLen) continue;
                    if(nlen <= bestLen) continue;

                    bool match = true;
                    for(uint8_t k = 0; k < nlen && match; k++) {
                        match = (pgm_read_byte(&NGRAM_TABLE[j][k]) == _inBuf[i + k]);
                    }
                    if(match) {
                        bestIdx = j;
                        bestLen = nlen;
                    }
                }

                if(bestIdx != 0xFF) {
                    sym     = 0x80u | bestIdx;
                    advance = bestLen;
                }
            }
        }

        _encodeSymbol(sym);
        i += advance;
    }

    // Encode NUL end-of-message marker
    _encodeSymbol(0x00);

    // Pad partial byte with zero bits (MSB-first — zeros go to the right)
    if(_bitPos > 0) {
        _outBuf[_outLen++] = (uint8_t)(_bitBuf << (8u - _bitPos));
        _bitBuf = 0;
        _bitPos = 0;
    }

    _inLen = 0;
    if(_outLen == 0) return 0;
    return _rb.push(_outBuf, _outLen) ? _outLen : 0;
}
