name: Build Container

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sming:latest

      - name: Clone Sming repository
        run: git clone --branch develop https://github.com/SmingHub/Sming.git /opt/Sming

      - name: Install Esp8266
        run: /opt/Sming/Tools/install.sh Esp8266

      - name: Install Esp32
        run: /opt/Sming/Tools/install.sh Esp32